export const apartments = [
  {
    id: 1,
    title: "Cozy Studio Downtown",
    beds: 0,
    city: "Seattle, WA",
    price: 1200,
    sqft: 350,
    featured: true,
    features: ["1 Bathroom", "Laundry", "Near Transit"],
    description: "Compact studio ideal for students or single professionals.",
  },
  {
    id: 2,
    title: "Two Bedroom Suburb",
    beds: 2,
    city: "Austin, TX",
    price: 1800,
    sqft: 950,
    featured: false,
    features: ["2 Bathrooms", "Parking", "Backyard"],
    description: "Quiet neighborhood with easy highway access.",
  },
  {
    id: 3,
    title: "Modern One-Bed Near Park",
    beds: 1,
    city: "Portland, OR",
    price: 1400,
    sqft: 620,
    featured: false,
    features: ["1 Bathroom", "Balcony", "Park View"],
    description: "Bright one-bedroom overlooking the central park.",
  },
  {
    id: 4,
    title: "Loft Style Studio",
    beds: 0,
    city: "Brooklyn, NY",
    price: 1300,
    sqft: 480,
    featured: false,
    features: ["High Ceilings", "Open Plan", "Washer/Dryer"],
    description: "Industrial loft with exposed brick and lots of light.",
  },
  {
    id: 5,
    title: "Three Bedroom Family Home",
    beds: 3,
    city: "Raleigh, NC",
    price: 2400,
    sqft: 1450,
    featured: true,
    features: ["2 Bathrooms", "Garage", "Yard"],
    description: "Spacious home perfect for families, close to schools.",
  },
  {
    id: 6,
    title: "Downtown Two-Bed with View",
    beds: 2,
    city: "San Francisco, CA",
    price: 2000,
    sqft: 880,
    featured: true,
    features: ["City View", "Gym Access", "Secure Entry"],
    description: "Contemporary two-bedroom in the heart of downtown.",
  },
  {
    id: 7,
    title: "Budget One-Bed",
    beds: 1,
    city: "Detroit, MI",
    price: 950,
    sqft: 540,
    featured: false,
    features: ["1 Bathroom", "Street Parking"],
    description: "Affordable one-bedroom close to local shops.",
  },
  {
    id: 8,
    title: "Suburban Townhouse",
    beds: 2,
    city: "Houston, TX",
    price: 1700,
    sqft: 1100,
    featured: false,
    features: ["2 Floors", "Garage", "Patio"],
    description: "Townhouse with easy access to public transit and shopping.",
  },
  {
    id: 9,
    title: "Penthouse Suite",
    beds: 3,
    city: "New York, NY",
    price: 4200,
    sqft: 1800,
    featured: true,
    features: ["Rooftop Deck", "Concierge", "Panoramic Views"],
    description: "Luxury penthouse with premium finishes and skyline views.",
  },
  {
    id: 10,
    title: "Garden-Level Studio",
    beds: 0,
    city: "San Diego, CA",
    price: 1100,
    sqft: 400,
    featured: false,
    features: ["Patio", "Garden Access", "Pet Friendly"],
    description: "Cozy garden-level studio with private outdoor space.",
  },
  {
    id: 11,
    title: "Riverside One-Bed",
    beds: 1,
    city: "Miami, FL",
    price: 1500,
    sqft: 700,
    featured: false,
    features: ["River View", "Walking Trails Nearby"],
    description: "Peaceful one-bedroom located along the riverwalk.",
  },
  {
    id: 12,
    title: "Bright Two-Bed Condo",
    beds: 2,
    city: "Chicago, IL",
    price: 1850,
    sqft: 940,
    featured: false,
    features: ["Open Kitchen", "Balcony", "Assigned Parking"],
    description: "Well-lit condo with modern kitchen and balcony.",
  },
  {
    id: 13,
    title: "Shared House Room",
    beds: 1,
    city: "Minneapolis, MN",
    price: 700,
    sqft: 140,
    featured: false,
    features: ["Shared Kitchen", "Utilities Included"],
    description: "Private room in a friendly shared house; utilities included.",
  },
  {
    id: 14,
    title: "Studio Near University",
    beds: 0,
    city: "Boston, MA",
    price: 1050,
    sqft: 380,
    featured: false,
    features: ["Close to Campus", "Bike Storage"],
    description: "Small studio ideal for students within walking distance of campus.",
  },
  {
    id: 15,
    title: "Four Bedroom Home",
    beds: 4,
    city: "Nashville, TN",
    price: 3000,
    sqft: 1900,
    featured: true,
    features: ["3 Bathrooms", "Large Yard", "Basement"],
    description: "Large family home with plenty of storage and outdoor space.",
  },
  {
    id: 16,
    title: "Compact One-Bed Loft",
    beds: 1,
    city: "Denver, CO",
    price: 1450,
    sqft: 610,
    featured: false,
    features: ["Loft Bed", "Close to Cafes"],
    description: "Stylish loft with mezzanine sleeping area.",
  },
  {
    id: 17,
    title: "Renovated Two-Bed",
    beds: 2,
    city: "Philadelphia, PA",
    price: 1950,
    sqft: 980,
    featured: false,
    features: ["Updated Kitchen", "In-Unit Laundry"],
    description: "Recently renovated with new appliances and fixtures.",
  },
  {
    id: 18,
    title: "Quiet Basement Suite",
    beds: 1,
    city: "Phoenix, AZ",
    price: 900,
    sqft: 520,
    featured: false,
    features: ["Separate Entrance", "Utilities Partially Included"],
    description: "Basement suite with private entrance and separate utilities.",
  },
  {
    id: 19,
    title: "Artist's Studio",
    beds: 0,
    city: "Los Angeles, CA",
    price: 1250,
    sqft: 560,
    featured: false,
    features: ["Natural Light", "High Ceilings", "Studio Space"],
    description: "Open-plan studio popular with creatives and makers.",
  },
  {
    id: 20,
    title: "Corner Three-Bed",
    beds: 3,
    city: "Charlotte, NC",
    price: 2200,
    sqft: 1300,
    featured: true,
    features: ["Corner Unit", "Extra Windows", "Storage Locker"],
    description: "Spacious corner unit with abundant natural light and storage.",
  }
];

export const services = [
  {
    id: 1,
    title: "House Cleaning Service",
    category: "Home Services",
    city: "Seattle, WA",
    price_per_hour: 40,
    rating: 4.8,
    contact: "(206) 555-0101",
    description: "Reliable two-person cleaning teams, flexible scheduling, eco-friendly products.",
  },
  {
    id: 2,
    title: "Mobile Auto Detailing",
    category: "Automotive",
    city: "Austin, TX",
    price_per_job: 120,
    rating: 4.6,
    contact: "(512) 555-0112",
    description: "On-site full interior/exterior detailing; waterless options available.",
  },
  {
    id: 3,
    title: "Handyman — Small Repairs",
    category: "Home Services",
    city: "Brooklyn, NY",
    price_per_hour: 65,
    rating: 4.7,
    contact: "(718) 555-0199",
    description: "Experienced with carpentry, mounting TVs, minor plumbing and electrical fixes.",
  },
  {
    id: 4,
    title: "Tutoring — Math & Science",
    category: "Education",
    city: "Raleigh, NC",
    price_per_hour: 55,
    rating: 4.9,
    contact: "(919) 555-0144",
    description: "One-on-one tutoring for high-school and college students, in-person or remote.",
  },
  {
    id: 5,
    title: "Personal Fitness Trainer",
    category: "Wellness",
    city: "San Francisco, CA",
    price_per_session: 60,
    rating: 4.5,
    contact: "(415) 555-0133",
    description: "Customized plans, outdoor sessions, nutrition guidance included.",
  },
  {
    id: 6,
    title: "Computer Repair & Setup",
    category: "Tech Services",
    city: "Detroit, MI",
    price_per_hour: 70,
    rating: 4.4,
    contact: "(313) 555-0177",
    description: "Hardware diagnostics, OS installs, data recovery and home network setup.",
  },
  {
    id: 7,
    title: "Pet Sitting / Dog Walking",
    category: "Pet Care",
    city: "Houston, TX",
    price_per_visit: 20,
    rating: 4.9,
    contact: "(713) 555-0122",
    description: "Daily visits, overnight stays, medication administration for pets.",
  },
  {
    id: 8,
    title: "Landscape & Garden Care",
    category: "Home Services",
    city: "San Diego, CA",
    price_per_job: 150,
    rating: 4.6,
    contact: "(619) 555-0166",
    description: "Seasonal lawn care, planting, and light hardscaping services.",
  },
  {
    id: 9,
    title: "Photography — Events & Portraits",
    category: "Creative",
    city: "Miami, FL",
    price_per_hour: 120,
    rating: 4.7,
    contact: "(305) 555-0188",
    description: "Event coverage, headshots, and family portraits; packages available.",
  },
  {
    id: 10,
    title: "Home Appliance Repair",
    category: "Home Services",
    city: "Chicago, IL",
    price_per_call: 85,
    rating: 4.3,
    contact: "(312) 555-0155",
    description: "Repair and maintenance for washers, dryers, refrigerators and ranges.",
  }
];

export const vehicles = [
  {
    id: 1,
    make: "Toyota",
    model: "Camry",
    year: 2017,
    price: 13500,
    mileage: 55000,
    city: "Austin, TX",
    features: ["Bluetooth", "Backup Camera", "Cruise Control"],
    description: "Well-maintained sedan; single owner, recent service history.",
    image: "/images/vehicles/vehicle1.svg",
  },
  {
    id: 2,
    make: "Honda",
    model: "Civic",
    year: 2018,
    price: 14200,
    mileage: 48000,
    city: "Seattle, WA",
    features: ["Fuel Efficient", "Lane Assist"],
    description: "Reliable commuter car with excellent fuel economy.",
    image: "/images/vehicles/vehicle2.svg",
  },
  {
    id: 3,
    make: "Ford",
    model: "F-150",
    year: 2015,
    price: 22000,
    mileage: 90000,
    city: "Raleigh, NC",
    features: ["4x4", "Tow Package"],
    description: "Work-ready pickup with bed liner and tow hitch.",
    image: "/images/vehicles/vehicle3.svg",
  },
  {
    id: 4,
    make: "Tesla",
    model: "Model 3",
    year: 2020,
    price: 32000,
    mileage: 30000,
    city: "San Francisco, CA",
    features: ["Autopilot", "Electric"],
    description: "Mid-range Model 3 with good battery health and features.",
    image: "/images/vehicles/vehicle4.svg",
  },
  {
    id: 5,
    make: "Chevrolet",
    model: "Malibu",
    year: 2016,
    price: 10500,
    mileage: 76000,
    city: "Detroit, MI",
    features: ["Bluetooth", "Cruise Control"],
    description: "Comfortable midsize sedan, clean interior.",
    image: "/images/vehicles/vehicle5.svg",
  },
  {
    id: 6,
    make: "BMW",
    model: "X3",
    year: 2019,
    price: 29500,
    mileage: 42000,
    city: "New York, NY",
    features: ["All Wheel Drive", "Sunroof"],
    description: "Luxury compact SUV with premium interior and recent maintenance.",
    image: "/images/vehicles/vehicle6.svg",
  },
  {
    id: 7,
    make: "Nissan",
    model: "Leaf",
    year: 2019,
    price: 11500,
    mileage: 36000,
    city: "San Diego, CA",
    features: ["Electric", "Low Running Cost"],
    description: "Affordable electric hatchback with good range for city driving.",
    image: "/images/vehicles/vehicle7.svg",
  },
  {
    id: 8,
    make: "Jeep",
    model: "Wrangler",
    year: 2014,
    price: 18500,
    mileage: 98000,
    city: "Houston, TX",
    features: ["4x4", "Removable Top"],
    description: "Rugged off-road ready Jeep with aftermarket tires.",
    image: "/images/vehicles/vehicle8.svg",
  },
  {
    id: 9,
    make: "Subaru",
    model: "Outback",
    year: 2017,
    price: 18500,
    mileage: 67000,
    city: "Denver, CO",
    features: ["All Wheel Drive", "Roof Rails"],
    description: "Versatile wagon with good cargo room and safety features.",
    image: "/images/vehicles/vehicle9.svg",
  },
  {
    id: 10,
    make: "Hyundai",
    model: "Elantra",
    year: 2020,
    price: 15000,
    mileage: 24000,
    city: "Phoenix, AZ",
    features: ["Fuel Efficient", "Apple CarPlay"],
    description: "Late-model compact with warranty remaining.",
    image: "/images/vehicles/vehicle10.svg",
  }
];

export const jobs = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "BrightWeb",
    city: "San Francisco, CA",
    salary: "100000-120000",
    type: "Full-time",
    posted: "2025-11-01",
    description: "Work on customer-facing web apps using modern JavaScript frameworks.",
  },
  {
    id: 2,
    title: "Registered Nurse",
    company: "Raleigh Medical Center",
    city: "Raleigh, NC",
    salary: "65000-85000",
    type: "Full-time",
    posted: "2025-10-28",
    description: "Provide patient care in a fast-paced hospital environment.",
  },
  {
    id: 3,
    title: "Graphic Designer",
    company: "Studio Nine",
    city: "Brooklyn, NY",
    salary: "50000-70000",
    type: "Part-time",
    posted: "2025-11-05",
    description: "Create marketing assets and campaign visuals; portfolio required.",
  },
  {
    id: 4,
    title: "Delivery Driver",
    company: "Metro Couriers",
    city: "Austin, TX",
    salary: "16-20/hr",
    type: "Contract",
    posted: "2025-11-03",
    description: "Local deliveries, reliable vehicle required.",
  },
  {
    id: 5,
    title: "Data Analyst",
    company: "InsightWorks",
    city: "Chicago, IL",
    salary: "75000-95000",
    type: "Full-time",
    posted: "2025-10-30",
    description: "Analyze customer data to generate actionable business insights.",
  },
  {
    id: 6,
    title: "Barista",
    company: "Corner Roast",
    city: "Portland, OR",
    salary: "14-17/hr",
    type: "Part-time",
    posted: "2025-11-06",
    description: "Friendly customer service; morning shift availability preferred.",
  },
  {
    id: 7,
    title: "Project Manager",
    company: "BuildRight",
    city: "Charlotte, NC",
    salary: "90000-110000",
    type: "Full-time",
    posted: "2025-11-02",
    description: "Manage cross-functional teams delivering software projects.",
  },
  {
    id: 8,
    title: "Warehouse Associate",
    company: "QuickShip",
    city: "Houston, TX",
    salary: "13-16/hr",
    type: "Full-time",
    posted: "2025-11-04",
    description: "Picking, packing, and shipping; forklift certification a plus.",
  },
  {
    id: 9,
    title: "UX Researcher",
    company: "UserFirst",
    city: "Boston, MA",
    salary: "85000-105000",
    type: "Full-time",
    posted: "2025-10-27",
    description: "Conduct user interviews, surveys, and usability studies.",
  },
  {
    id: 10,
    title: "Retail Store Manager",
    company: "CityThreads",
    city: "Minneapolis, MN",
    salary: "48000-62000",
    type: "Full-time",
    posted: "2025-11-07",
    description: "Oversee daily store operations, staffing, and merchandising.",
  }
];

export const forSale = [
  {
    id: 1,
    title: "Charming Bungalow",
    price: 325000,
    beds: 3,
    baths: 2,
    sqft: 1400,
    city: "Seattle, WA",
    listing_date: "2025-10-15",
    features: ["Hardwood Floors", "Fenced Yard", "Garage"],
    description: "Well-maintained bungalow in a quiet neighborhood, close to transit and parks.",
  },
  {
    id: 2,
    title: "Modern Condo",
    price: 450000,
    beds: 2,
    baths: 2,
    sqft: 980,
    city: "San Francisco, CA",
    listing_date: "2025-11-01",
    features: ["Balcony", "Gym", "Secure Entry"],
    description: "Contemporary condo with amenities and downtown access.",
  },
  {
    id: 3,
    title: "Suburban Split-Level",
    price: 289000,
    beds: 3,
    baths: 2,
    sqft: 1600,
    city: "Raleigh, NC",
    listing_date: "2025-09-20",
    features: ["Basement", "Backyard", "Nearby Schools"],
    description: "Comfortable family home with updated kitchen and large yard.",
  },
  {
    id: 4,
    title: "Downtown Loft",
    price: 375000,
    beds: 1,
    baths: 1,
    sqft: 720,
    city: "Brooklyn, NY",
    listing_date: "2025-11-05",
    features: ["Exposed Brick", "High Ceilings"],
    description: "Open-plan loft ideal for a creative professional.",
  },
  {
    id: 5,
    title: "Ranch With Acreage",
    price: 525000,
    beds: 4,
    baths: 3,
    sqft: 2300,
    city: "Austin, TX",
    listing_date: "2025-10-01",
    features: ["Large Lot", "Barn", "Workshop"],
    description: "Expansive ranch property with room for hobby farming.",
  },
  {
    id: 6,
    title: "Cozy Cottage",
    price: 210000,
    beds: 2,
    baths: 1,
    sqft: 820,
    city: "Portland, OR",
    listing_date: "2025-09-10",
    features: ["Garden", "Updated Kitchen"],
    description: "Cute cottage with a private garden and off-street parking.",
  },
  {
    id: 7,
    title: "Luxury Townhouse",
    price: 675000,
    beds: 3,
    baths: 3,
    sqft: 1500,
    city: "New York, NY",
    listing_date: "2025-11-07",
    features: ["Rooftop Deck", "Concierge", "Private Garage"],
    description: "High-end townhouse in a prime neighborhood.",
  },
  {
    id: 8,
    title: "Fixer Upper",
    price: 165000,
    beds: 3,
    baths: 1,
    sqft: 1100,
    city: "Detroit, MI",
    listing_date: "2025-10-22",
    features: ["Needs Renovation", "Good Lot"],
    description: "Great investment opportunity for renovation-minded buyers.",
  },
  {
    id: 9,
    title: "Coastal Retreat",
    price: 820000,
    beds: 4,
    baths: 3,
    sqft: 2100,
    city: "San Diego, CA",
    listing_date: "2025-08-30",
    features: ["Ocean Views", "Deck", "Open Kitchen"],
    description: "Beautiful coastal home with panoramic ocean views.",
  },
  {
    id: 10,
    title: "New Construction Single Family",
    price: 399000,
    beds: 3,
    baths: 2,
    sqft: 1250,
    city: "Houston, TX",
    listing_date: "2025-11-02",
    features: ["Energy Efficient", "Attached Garage"],
    description: "New build with modern finishes and warranty.",
  }
];
