export const apartments = [
  {
    id: 1,
    title: "Cozy Studio Downtown",
    beds: 0,
    city: "New York, NY",
    price: 1800,
    location: "123 Broadway, New York, NY",
    features: ["1 Bathroom", "Laundry", "Near Transit"],
  },
  {
    id: 2,
    title: "Two Bedroom Suburb",
    beds: 2,
    city: "San Francisco, CA",
    price: 3200,
    location: "456 Oak St, San Francisco, CA",
    features: ["2 Bathrooms", "Parking", "Backyard"],
  },
  {
    id: 3,
    title: "Modern One-Bedroom Loft",
    beds: 1,
    city: "Chicago, IL",
    price: 1500,
    location: "789 Pine St, Chicago, IL",
    features: ["1 Bathroom", "Gym Access", "Pet Friendly"],
  },
  {
    id: 4,
    title: "Spacious Three Bedroom Apartment",
    beds: 3,
    city: "Austin, TX",
    price: 2500,
    location: "321 Elm St, Austin, TX",
    features: ["2 Bathrooms", "Parking", "Balcony"],
  },
  {
    id: 5,
    title: "Luxury Downtown Condo",
    beds: 2,
    city: "Los Angeles, CA",
    price: 4000,
    location: "654 Market St, Los Angeles, CA",
    features: ["2 Bathrooms", "Pool", "Doorman", "Gym Access"],
  },
  {
    id: 6,
    title: "Charming Cottage",
    beds: 1,
    city: "Seattle, WA",
    price: 1700,
    location: "987 Maple Ave, Seattle, WA",
    features: ["1 Bathroom", "Backyard", "Pet Friendly"],
  },
  {
    id: 7,
    title: "Penthouse Suite",
    beds: 4,
    city: "Miami, FL",
    price: 5500,
    location: "159 Sunset Blvd, Miami, FL",
    features: ["3 Bathrooms", "Rooftop Terrace", "Gym Access", "Parking"],
  },
  {
    id: 8,
    title: "Cozy One Bedroom Near Park",
    beds: 1,
    city: "Boston, MA",
    price: 2000,
    location: "753 Oak St, Boston, MA",
    features: ["1 Bathroom", "Near Park", "Laundry"],
  }
];
